name: S3 Deploy
on:
  push:
    # branches: [ master ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
# Commenting
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking-out repo (under $GITHUB_WORKSPACE)
        uses: actions/checkout@master

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint

#      - name: Test
#        run: npm run test

      - name: Build
        run: npm run build

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
        run: |
          npm run s3:rm
          npm run s3:cp

#      - name: Notification
#        uses: 12345/action-slack@v2.6.0
#        with:
#          status: ${{ job.status }}
#          author_name: github actions - goytoot
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
